### ISSUE TITLE
python_package installation fails because install path isn't on PYTHONPATH

### ISSUE THREAD

**Issue by moooeeeep** [rock-core/autobuild#106]
Recently we are facing build errors when building and installing Python packages, e.g.:

    running install
    Checking .pth file support in /home/moooeeeep/workspace/install/some/package/lib/python3.6/site-packages/
    /usr/bin/python3 -E -c pass
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    TEST FAILED: /home/moooeeeep/workspace/install/some/package/lib/python3.6/site-packages/ does NOT support .pth files
    error: bad install directory or PYTHONPATH

    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /home/moooeeeep/workspace/install/some/package/lib/python3.6/site-packages/

    and your PYTHONPATH environment variable currently contains:

        ''

    Here are some of your options for correcting the problem:

    * You can choose a different installation directory, i.e., one that is
      on PYTHONPATH or supports .pth files

    * You can add the installation directory to the PYTHONPATH environment
      variable.  (It must then also be on PYTHONPATH whenever you run
      Python and want to use the package(s) you are installing.)

    * You can set up the installation directory to support ".pth" files by
      using one of the approaches described here:

      https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

    Please make the appropriate changes for your system and try again.

Apparantly the location to which the package is installed needs to be on the PYTHONPATH. Currently the PYTHONPATH entry is added after the installation. As the PYTHONPATH entry is added even when the build fails due to this error, the second run of amake is usually successful. But obviously this is still annoying.

I'm not sure if it is possible to disable this check or the error, to not fail the build. Potentially this is related to the separate prefix dirs setting.

On my machine I usually work around this by adjusting the [install command](https://github.com/rock-core/autobuild/blob/master/lib/autobuild/packages/python.rb#L44) to install to `--user` or via `pip install .`. But maybe this would affect other workflows that rely on these separate installation locations? 

Potentially related: https://github.com/rock-core/autoproj/issues/313

The URL given in the error message is broken, I think it was meant to refer to this content: https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations

**Comment by g-arjones** [comment]
@moooeeeep Could you try #113, please?
