### ISSUE TITLE
PKG_CONFIG_PATH on systems using lib64 does not match install location of many packages

### ISSUE THREAD

**Issue by pierrewillenbrockdfki** [rock-core/autobuild#118]
This may or may not be a bug in autobuild.

On systems that use lib64 for their 64 bit libraries, the PKG_CONFIG_PATH from autobuild does not pick up the many install prefixes that unconditionally install their pkg-config .pc files in lib/pkgconfig (likewise for their libraries).

default_pkgconfig_search_suffixes in lib/autobuild/environment.rb uses pkg-config to find suffix paths to look for.
On this system, pkg-config results in:

```
pkg-config --variable pc_path pkg-config
/usr/lib64/pkgconfig:/usr/share/pkgconfig
```

thus default_pkgconfig_search_suffixes results in "lib64/pkgconfig","share/pkgconfig"

I see two ways to resolve this:

1. Unconditionally add lib/pkgconfig to default_pkgconfig_search_suffixes. I can imagine this to require additional changes to the search paths in e.g. typelib or orogen, i did not explore this way.
2. Have all packages install at least their .pc files in the system specific suffixes. I have a workspace where i did that and moved all library installation to lib64 as well, but only tested everything compiles(including orogen packages). This also touches RTT_COMPONENT_PATH generation, although it is empty for me in any case. Also orogen and orogen plugin templates had to be adjusted.

For 2., i relied on GNUInstallDirs to provide CMAKE_INSTALL_LIBDIR ("lib", "lib32", "lib64" or "lib/arch"), assuming that it matches pkg-config builtin path. (And one would hope distribution maintainers would make sure it does.)
I did find one cmake package that used LIB_SUFFIX, where the package_set would have had to provide that as parameter to cmake. I changed that to GNUInstallDirs method. The autotools packages require a parameter to their configure script: "--libdir=${exec_prefix}/lib64". Here, i did not try to determine the correct value from the system, yet.

I consider 2. the more correct approach, because for those packages, that could be installed system wide, installing 64bit libraries in lib on systems using lib64 would be a bug.

**Comment by doudou** [comment]
I'd assume that we are talking about Rock packages here. But then, I guess other packages might also have lib/pkgconfig hardcoded.

(2) would definitely be an improvement for Rock packages. Now, if other packages behave the same way, we'd have to do (1) as well anyways.
