### ISSUE TITLE
Release with git --depth 1

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-core/autobuild#123]
I'd be interest in having a release with the shallow option from https://github.com/rock-core/autobuild/pull/117 (May 5).
The latest release v1.23.1 is from Mar 7.
Is there any plan for a new release?

**Comment by doudou** [comment]
Sorry @joaobrittoneto ... I overlooked that.

Done, as v1.24.0

https://github.com/rock-core/autobuild/releases/tag/v1.24.0

**Comment by doudou** [comment]
@g-arjones I was thinking it would be a good idea to give you the rights on the autobuild and autoproj gems ... would avoid me being the single point of failure for releases. What do you think ?
