### ISSUE TITLE
autobuild does NOT track the release correctly (if tag is given it still tracks a branch)

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autobuild#22]
It tracks sometimes the stable branch and does not create a detached_head (what i would assume when following a tag).

I tried in a rc-installation to use a old tag by chaning `vim autoproj/overrides.d/25-release.yml` to:

```
778 - slam/envire:
779     tag: stable-20140120
780     commit:
```

after a update slam/envire is still on stable state instead on the given commit. This causes that the release is NOT a pinned release until this PR get fixed and autobuild got released

**Comment by goldhoorn** [comment]
From what i see it is a missinterpretation of the autobuild behavior i created #23 for this (which solved this from my point of view)

The problem occurs if a release is switched and only update (without --reset) is called then the user don't get a feedback that the packages will not reseted automatically

**Comment by doudou** [comment]
This is the expected autobuild/autoproj behaviour. update will never get back in time, you have to use --reset for that. This was a change required to make developing on pinned packages possible (which is really really needed if one uses the snapshot feature extensively).

Adding a warning is a no-no for the same reason (will be a very common occurence in installations that use snapshotting)

It is a change of behaviour, hence your confusion, but is IMO for the best.
