### ISSUE TITLE
autobuild 1.10: pkg.resolved_env does result in a bare Object

### ISSUE THREAD

**Issue by pierrewillenbrockdfki** [rock-core/autobuild#36]
https://github.com/rock-core/autobuild/blob/40bd387727bca8f52a7ac193ea5720b05c225294/lib/autobuild/package.rb#L620

Looks like ENV.dup is not the right thing to do. Not sure if .clone is more appropriate, or .to_h.dup, or just .to_h.

**Comment by doudou** [comment]
Just release 1.9.6 that fixes the issue. Hash[ENV] works, I've reported this as a bug (https://bugs.ruby-lang.org/issues/13799)
