### ISSUE TITLE
display logfile of failed package

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-core/autobuild#87]
In case a build process fail, it indicate the logfile and prints the last 10 lines of the file.
It would be nice to have an option do display the whole file, or select the number of lines to be displayed.

Something like `autoproj build --display-failed-log`

**Comment by doudou** [comment]
You can set Autobuild.displayed_error_line_count in e.g. `~/.autoprojrc`. Set to `Float::INFINITY` to have no limit

**Comment by planthaber** [comment]
Or set it in your autoproj/init.rb:

Autobuild.displayed_error_line_count="ALL"

**Comment by doudou** [comment]
@joaobrittoneto since it seems that your wishes were granted already, I'm closing this. Please feel free to re-open if there's anything to add.
