### ISSUE TITLE
provide --depth option for git repositories

### ISSUE THREAD

**Issue by planthaber** [rock-core/autobuild#93]
I often clone simulation models into workspaces. These repositories tend to be rather big (500MB) after some time due to storage of meshes and binary files, etc.

Often these models are not edited from within the workspace, but only used. So I'd like to set "git clone"s --depth option via an override like this:

```yaml
- models/robots/myrobot:
  depth: 1
  single_branch: true
```
While "single_branch" already works and helps, there is no parameter for depth that is forwarded to the git clone call.
At least I did not find any in the documentation: https://rubydoc.info/gems/autobuild/Autobuild/Git

In my case this would reduce the folder size from 500mb to 100mb.

I guess this is not as easy as it seems, as afaik also updates (git pull) need to use  the --depth=1 option, otherwise they pull the full repo.

**Comment by g-arjones** [comment]
I think this is pretty easy to implement, yes. All you have to change is here: https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb

**Comment by doudou** [comment]
Just as a side note (I'm totally fine with adding support for that), storing big binary files in Git is generally considered just not a very great idea. Autobuild already has support for [LFS](https://www.rock-robotics.org/rock-and-syskit/workspace/add_packages.html#git-lfs) for this.

Now, I'm totally open for the addition of handling of the `depth` argument. If you do implement the feature, please consider adding a way to globally set it (as e.g. a class-level attribute `Autobuild::Git.default_depth`), which would be helpful for CI.
