### ISSUE TITLE
git recursive submodules

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-core/autobuild#94]
I have a package with recursive submodules and I found a strange behaviour within autobuild.

Doing `autoproj update pkg`, the HEAD of the last submodule is not on the commit indicated on the previous submodule.
I would need to do a `git submodule update --recursive` to make it correct.

I checked cloning the pkg with `git clone --branch=<branch> --recurse-submodule <git@package>` and there was no problem.

Checking the code, it seems a `--recursive` [here](https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb#L1204) would be necessary. Although I'm not sure why `git clone --recurse-submodules` [here](https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb#L1198) didn't do it already.

**Comment by planthaber** [comment]
autoprojs default is not to recurse submodules at all.

In your source.yml you need to set "with_submodules: true" for your package in oder to tell autoproj to handle them correctly.

```yaml
    - models/robots/exo_model:
      dfkigit: models-robots/recupera_models/full-urdf
      with_submodules: true
```
--recurse-submodules is part of the clone_options variable:
https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb#L1183

**Comment by joaobrittoneto** [comment]
It's already `with_submodules: true`. 

The problem that I face is that the package has a submodule with a submodule, and the last submodule is not on the correct commit.

I'd expect the --recurse-submodules of clone_options to do it.
But it seems that the `git submodule update` here https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb#L1204 is the one that update at least the first submodule. (missing the --recursive for updating the nested submodules)

**Comment by planthaber** [comment]
Thats strage, the documentation says that

> https://git-scm.com/book/en/v2/Git-Tools-Submodules:
There is another way to do this which is a little simpler, however. If you pass --recurse-submodules to the git clone command, it will automatically initialize and update each submodule in the repository, including nested submodules if any of the submodules in the repository have submodules themselves.

Are you sure that "with_submodules" was enabled on the initial checkout?, if not, the initial clone and submodule setup was not executed. after this a normal "git pull" also updtaed the submodules. You can try deleting the folder to clone again or try:
```git submodule update --init --recursive``` inside the package.

**Comment by joaobrittoneto** [comment]
Sure the 'with_submodules' is present. 
Both `git clone --branch=<branch> --recurse-submodule <git@package>` and `git submodule update --init --recursive` works on puting the HEAD of the last submodule on the correct commit.

I found a bit suspected that the checkout method does a `git submodule update --init` after cloning with --recurse-submodule in clone_options. (In principal it would not be necessary, right?)

I guess an unit test with nested submodules would be ideal. But I'm not sure how to do it.

**Comment by doudou** [comment]
> I guess an unit test with nested submodules would be ideal. But I'm not sure how to do it.

I think that would be a very good idea.

The git tests work "simply" by manually creating repositories in various states, `git clone --bare` them and then creating tarballs.

In the unit tests, the `untar` helper then takes a tarball and un-tars it in a temporary directory.

I'm guessing that it could be solved in this case by combining multiple git repos in a single tarball (to make sure they are all un-tared in the same folder), and specifying the submodules using relative paths (which seem to be possible, I'm not using submodules so it's hard for me to know for sure)

The existing tests are probably a good reference for the rest of the tests (i.e. checking HEAD) https://github.com/rock-core/autobuild/blob/master/test/import/test_git.rb

**Comment by doudou** [comment]
(Closed by accident)

**Comment by joaobrittoneto** [comment]
[Unit test done](https://github.com/rock-core/autobuild/pull/97/commits/81dcd72f6057ae2f5549e00301955822bc5546ec). It replicates the problem with the nested submodules.
The tests pass by adding --recursive [here](https://github.com/rock-core/autobuild/pull/97/commits/0b95c28a2981a2eeb2f8d8f6b892f49cc9ff4198). Although I still think [--recurse-submodules](https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb#L1183) should do it on `checkout`.

While writing the test, I got in doubt about the  [local-only mode](https://github.com/rock-core/autobuild/blob/master/test/import/test_git.rb#L652). As far as I understood, the test is not consistent with the description. On the update method it uses [only-local](https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb#L1099) instead of local-only. But I may be missing something.

**Comment by g-arjones** [comment]
> Although I still think --recurse-submodules should do it on checkout

You don't need both `--recursive` and `--recurse-submodules`.

From git-clone(1):

```
       --recurse-submodules[=<pathspec]
           After the clone is created, initialize and clone submodules within based on the provided pathspec. If no pathspec is provided, all
           submodules are initialized and cloned. This option can be given multiple times for pathspecs consisting of multiple entries. The resulting
           clone has submodule.active set to the provided pathspec, or "." (meaning all submodules) if no pathspec is provided.

           Submodules are initialized and cloned using their default settings. This is equivalent to running git submodule update --init --recursive
           <pathspec> immediately after the clone is finished. This option is ignored if the cloned repository does not have a worktree/checkout (i.e.
           if any of --no-checkout/-n, --bare, or --mirror is given)
```

The fix is to add do it in the update method.
